// <auto-generated />
using JWTDemo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace JWTDemo.Migrations
{
    [DbContext(typeof(BaseEntities))]
    partial class BaseEntitiesModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("JWTDemo.Data.Account", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateDate");

                    b.Property<string>("Email");

                    b.Property<string>("Password");

                    b.Property<string>("Tel");

                    b.Property<string>("UserName");

                    b.HasKey("ID");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("JWTDemo.Data.AccountRole", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccountID");

                    b.Property<int>("RoleID");

                    b.HasKey("ID");

                    b.HasIndex("AccountID");

                    b.HasIndex("RoleID");

                    b.ToTable("AccountRole");
                });

            modelBuilder.Entity("JWTDemo.Data.ApiCollection", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ApiName")
                        .IsRequired();

                    b.Property<string>("Path")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("ApiCollection");
                });

            modelBuilder.Entity("JWTDemo.Data.Role", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("RoleName");

                    b.HasKey("ID");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("JWTDemo.Data.RoleApi", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ApiID");

                    b.Property<int>("RoleID");

                    b.HasKey("ID");

                    b.HasIndex("ApiID");

                    b.HasIndex("RoleID");

                    b.ToTable("RoleApi");
                });

            modelBuilder.Entity("JWTDemo.Data.AccountRole", b =>
                {
                    b.HasOne("JWTDemo.Data.Account", "Account")
                        .WithMany("AccountRole")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("JWTDemo.Data.Role", "Role")
                        .WithMany("AccountRole")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JWTDemo.Data.RoleApi", b =>
                {
                    b.HasOne("JWTDemo.Data.ApiCollection", "Apis")
                        .WithMany("RoleApi")
                        .HasForeignKey("ApiID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("JWTDemo.Data.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
